- name: Create Gogs root directory
  ansible.builtin.file:
    path: "{{ gogs_root_dir }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Render docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gogs_root_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Start Gogs stack
  community.docker.docker_compose_v2:
    project_src: "{{ gogs_root_dir }}"
    state: present
